import Head from "next/head";
import LoginButton from "../components/login-btn";
import { getSession } from "next-auth/react";
import GrocerySearch from "../components/GrocerySearch";
import GroceryList from "../components/GroceryList";
import { useState } from "react";

export default function Home({ session }) {
  const [itemList, setItemList] = useState([]);
  return (
    <div>
      <Head>
        <title>Grocery List</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.shareicon.net/data/128x128/2016/05/05/760099_food_512x512.png"
        />
      </Head>

      <main>
        <LoginButton />
        <h1>Welcome to your Grocery List!</h1>
        <GrocerySearch setItemList={setItemList} />
        <GroceryList itemList={itemList} />
      </main>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/api/auth/signin",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
